### ISSUE TITLE
RSS feed for rubenpieters.github.io

### ISSUE THREAD

**Issue by haroldcarr** [rubenpieters/HumanDateTime#1]
Is there an RSS/Atom feed for your blog?

Great stuff in your blog.

ps: I apologize for hijacking this issue list, but only way I could figure how to make contact.

**Comment by rubenpieters** [comment]
added atom feed:
https://rubenpieters.github.io/feed.xml

**Comment by haroldcarr** [comment]
Thanks (for the feed and the posts)
